name: Build Void Windows IDE

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: voideditor/void
        ref: ${{ github.event.inputs.branch }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Install windows-build-tools
      run: npm install --global windows-build-tools

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Cache yarn cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: |
        yarn --verbose

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Update VSCode engine version
      run: |
        $packageJsonPath = Join-Path $PWD "package.json"
        $packageJson = Get-Content -Path $packageJsonPath -Raw | ConvertFrom-Json
        $typesVersion = yarn list --pattern "@types/vscode" --depth=0 | Select-String -Pattern "@types/vscode@(\d+\.\d+\.\d+)" | ForEach-Object { $_.Matches.Groups[1].Value }
        Write-Host "Current @types/vscode version: $typesVersion"

        if (-not $packageJson.PSObject.Properties.Name -contains "engines") {
            $packageJson | Add-Member -NotePropertyName "engines" -NotePropertyValue @{}
        }

        if (-not $packageJson.engines) {
            $packageJson.engines = @{}
        }

        if (-not $packageJson.engines.PSObject.Properties.Name -contains "vscode") {
            $packageJson.engines | Add-Member -NotePropertyName "vscode" -NotePropertyValue "^$typesVersion"
        } else {
            $packageJson.engines.vscode = "^$typesVersion"
        }

        Write-Host "Updated engines.vscode to: ^$typesVersion"
        $packageJson | ConvertTo-Json -Depth 100 | Set-Content -Path $packageJsonPath
        Get-Content -Path $packageJsonPath

    - name: Build Void
      run: |
        yarn gulp vscode-win32-x64

    - name: Check build output
      run: |
        if (Test-Path .\VSCode-win32-x64) {
          echo "Build output exists"
        } else {
          echo "Build output does not exist"
          exit 1
        }

    - name: Create Release ZIP
      run: |
        Compress-Archive -Path .\VSCode-win32-x64 -DestinationPath .\VoidIDE-Windows.zip
        if (Test-Path .\VoidIDE-Windows.zip) {
          echo "ZIP file created successfully"
        } else {
          echo "Failed to create ZIP file"
          exit 1
        }

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: VoidIDE-Windows
        path: .\VoidIDE-Windows.zip

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          **/*.log
          **/yarn-error.log
          **/npm-debug.log
