name: Build Void Windows IDE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Enable Corepack
      run: corepack enable

    - name: Install Root Dependencies
      run: yarn install

    - name: Build Extension
      working-directory: extensions/void
      run: |
        yarn install
        yarn build

    - name: Compile the IDE
      run: yarn compile

    - name: Bundle the IDE
      run: yarn gulp vscode-win32-x64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: void-windows-ide
        path: .build/electron/code-*
